--- 
- hosts: webserverhosts
  become: yes
  tasks:
     - name: i want to apache on ubuntu node
       apt:
          name: apache2
          state: present
          
     - name: i want to start webserver on ubuntu server
       service:
              name: apache2
              state: started 
    
                 